import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { AdminAnalytics } from "../web/pages/admin-analytics";
const range={start_date:"2026-10-06",end_date:"2026-10-06",time_zone:"America/Chicago"};
const base={schema_version:1,range,generated_at:"2026-10-06T17:00:00Z",coverage:{first_event_at:"2026-10-01T15:00:00Z",last_event_at:"2026-10-06T16:00:00Z"}};
const signals={...base,summary:{signups:2,activations:null,payments:1,paying_accounts:1,amount_minor:2500,currency:"USD"},daily:[{date:range.start_date,signups:2,activations:null,payments:1,amount_minor:2500}],activation_coverage:{status:"unavailable",since:null}};
const account=(n:number)=>({account_ref:`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,display_name:null,email:null,signup_at:"2026-10-06T15:00:00Z",last_active_at:"2026-10-06T16:00:00Z",events_in_range:2,activated_at:null,payments:1,amount_minor:2500,acquisition:{source:null,medium:null,campaign:null,landing_path:null,handoff_status:"none",capture_quality:"pending"},summary:"How this account first arrived was not captured. No completed run has been recorded."});
beforeEach(()=>{vi.useFakeTimers({toFake:["Date"]});vi.setSystemTime(new Date("2026-10-06T17:00:00Z"));});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.useRealTimers();});
test("signals use today's calendar range and real payment amounts while unavailable activation stays unknown",async()=>{
 const fetcher=vi.fn().mockResolvedValue(Response.json(signals));vi.stubGlobal("fetch",fetcher);
 render(<AdminAnalytics/>);
 await screen.findByText("1 paying account · $25.00 purchased");
 expect((screen.getByLabelText("From date") as HTMLInputElement).value).toBe("2026-10-06");
 expect(fetcher.mock.calls[0][0]).toContain("start_date=2026-10-06&end_date=2026-10-06&time_zone=America%2FChicago");
 const activation=screen.getByRole("heading",{name:"Activated accounts"}).closest("article")!;
 expect(within(activation).getByText("—")).toBeTruthy();
 expect(screen.getByText(/First successful executions are not currently being tracked/)).toBeTruthy();
 fireEvent.change(screen.getByLabelText("From date"),{target:{value:"2026-10-07"}});
 fireEvent.click(screen.getByRole("button",{name:"Apply"}));
 expect(screen.getByRole("alert").textContent).toMatch(/end date must be on or after/);
 expect(fetcher).toHaveBeenCalledTimes(1);
 fireEvent.change(screen.getByLabelText("From date"),{target:{value:"2026-10-01"}});
 fireEvent.click(screen.getByRole("button",{name:"Apply"}));
 await waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(2));
 expect(fetcher.mock.calls[1][0]).toContain("start_date=2026-10-01");
});
test("an old delayed report cannot overwrite a newly selected date range",async()=>{
 let resolveOld!:(value:Response)=>void;
 const old=new Promise<Response>(resolve=>{resolveOld=resolve;});
 const fetcher=vi.fn().mockReturnValueOnce(old).mockResolvedValue(Response.json(signals));vi.stubGlobal("fetch",fetcher);
 render(<AdminAnalytics/>);
 fireEvent.change(screen.getByLabelText("Calendar preset"),{target:{value:"yesterday"}});
 await screen.findByText("1 paying account · $25.00 purchased");
 resolveOld(Response.json({...signals,summary:{...signals.summary,payments:999,paying_accounts:999}}));
 await waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(2));
 expect(screen.queryByText(/999 paying/)).toBeNull();
 expect((screen.getByLabelText("From date") as HTMLInputElement).value).toBe("2026-10-05");
});
test("journey pages and event pages request the correct cursor, retain the range, and display dollars",async()=>{
 const requests:any[]=[];
 vi.stubGlobal("fetch",vi.fn(async(url:string,init:RequestInit)=>{
  if(url.startsWith("/api/product-signals"))return Response.json(signals);
  const request=JSON.parse(String(init.body));requests.push(request);
  if(request.kind==="journeys")return Response.json({...base,kind:"journeys",items:[account(request.cursor?2:1)],next_cursor:request.cursor?null:"accountpage2"});
  return Response.json({...base,kind:"journey",account:account(2),events:[{event_id:request.cursor?"later":"first",name:request.cursor?"run_credit_purchased":"run_account_created",occurred_at:"2026-10-06T15:00:00Z",source_app:"run",page_host:null,page_path:null,properties:request.cursor?{amount_minor:2500,currency:"USD"}:{}}],next_cursor:request.cursor?null:"eventpage2"});
 }));
 const user=userEvent.setup();render(<AdminAnalytics/>);
 await screen.findByText("1 paying account · $25.00 purchased");
 await user.click(screen.getByRole("tab",{name:"User journeys"}));
 await screen.findByRole("button",{name:/View journey.*000001/});
 await user.click(screen.getByRole("button",{name:"Next"}));
 await user.click(await screen.findByRole("button",{name:/View journey.*000002/}));
 await screen.findByText("Account created");
 await user.click(screen.getByRole("button",{name:"Later events"}));
 await screen.findByText("Credit purchased");
 await user.click(screen.getByText("Event details"));
 const dialog=screen.getByRole("dialog");expect(within(dialog).getByText("Amount").nextElementSibling?.textContent).toBe("$25.00");
 expect(requests.find(r=>r.cursor==="accountpage2")?.kind).toBe("journeys");
 expect(requests.find(r=>r.cursor==="eventpage2")?.account_ref).toBe(account(2).account_ref);
 expect(requests.every(r=>r.start_date===range.start_date&&r.end_date===range.end_date)).toBe(true);
 await user.click(screen.getByRole("button",{name:"Close"}));
 fireEvent.change(screen.getByLabelText("Calendar preset"),{target:{value:"yesterday"}});
 await waitFor(()=>expect(requests.at(-1).start_date).toBe("2026-10-05"));
 expect(requests.at(-1).cursor).toBeUndefined();
});
test("unconnected journeys do not hide database signals; a forbidden response clears loaded figures",async()=>{
 let forbidden=false;
 vi.stubGlobal("fetch",vi.fn(async(url:string)=>forbidden?new Response("This account may not use the admin site",{status:403}):url.startsWith("/api/product-signals")?Response.json(signals):Response.json({error:"report_not_configured"},{status:503})));
 const user=userEvent.setup();render(<AdminAnalytics/>);
 await screen.findByText("1 paying account · $25.00 purchased");
 await user.click(screen.getByRole("tab",{name:"User journeys"}));
 await screen.findByText("Waiting for the tracking connection");
 await user.click(screen.getByRole("tab",{name:"Product signals"}));
 await screen.findByText("1 paying account · $25.00 purchased");
 forbidden=true;await user.click(screen.getByRole("button",{name:"Refresh"}));
 await screen.findByRole("heading",{name:"Admin access required"});
 expect(screen.queryByText("1 paying account · $25.00 purchased")).toBeNull();
});
