// Writes sandbox/v8-exec/src/bootstrap.js from SANDBOX_BOOTSTRAP, which the v8-exec binary compiles in
// (tests/v8-exec.test.ts checks the two agree). Usage: node --experimental-strip-types scripts/gen-v8-bootstrap.ts
import { writeFileSync } from "node:fs";
import { SANDBOX_BOOTSTRAP } from "../src/sandbox-bootstrap.ts";

writeFileSync(new URL("../sandbox/v8-exec/src/bootstrap.js", import.meta.url), `// Generated by scripts/gen-v8-bootstrap.ts from src/sandbox-bootstrap.ts: do not edit.${SANDBOX_BOOTSTRAP}`);
